create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null check (price > 0),
  category text not null check (category in (
    'Очки корригирующие',
    'Очки солнцезащитные',
    'Очки для водителя',
    'Очки спортивные'
  )),
  description text not null default '',
  image text not null,
  is_top boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Public can view active products"
on public.products for select
using (active = true);

insert into public.products (name, price, category, description, image, is_top)
select * from (values
  ('Kofanov Classic Black', 4990, 'Очки солнцезащитные', 'Лёгкая классическая оправа на каждый день.', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900', true),
  ('Kofanov Silver', 5990, 'Очки корригирующие', 'Современная модель с универсальной посадкой.', 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=900', true),
  ('Kofanov Brown', 4490, 'Очки для водителя', 'Тёплый оттенок оправы и минималистичный дизайн.', 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=900', true),
  ('Kofanov Premium', 7990, 'Очки спортивные', 'Премиальная модель с акцентом на детали.', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900', true)
) as seed(name, price, category, description, image, is_top)
where not exists (select 1 from public.products);
